# Generated by Django 4.2.6 on 2023-10-23 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=75)),
                ('notes', models.TextField()),
                ('favorite_recipes', models.ManyToManyField(blank=True, to='recipes.recipe')),
            ],
        ),
    ]
