# Generated by Django 4.2.6 on 2023-10-23 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite_recipes',
        ),
    ]
