# Generated by Django 4.2.6 on 2023-10-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_alter_user_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(default='no_picture.jpg', upload_to='users'),
        ),
    ]
