# Generated by Django 4.2.6 on 2023-10-26 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_picture_user_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='pic',
            new_name='picture',
        ),
    ]
