# Generated by Django 4.2.6 on 2023-11-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0049_remove_recipe_creator_name_recipe_is_public_and_more'),
        ('users', '0008_rename_picture_user_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='favorite_recipes',
            field=models.ManyToManyField(blank=True, related_name='users_favorite_recipes', to='recipes.recipe'),
        ),
    ]
